# 项目相关配置
cc:
  # 名称
  name: CC_SERVER
  # 版本
  version: 0.0.1
  # 版权年份
  copyright: 2023
  # 文件路径 示例（ Windows配置D:/cc/uploadPath，Linux配置 /home/cc/uploadPath）
  profile: /
  # 获取ip地址开关
  address-enabled: true

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    max-retry-count: 5
    # 密码错误锁定时长
    lock-time: 10

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 1000
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# Spring配置
spring:
  application:
    name: java-serve
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root123456
    druid:
      # 主库数据源
      #      master:
      #        url: jdbc:mysql://localhost:3306/cc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: root
      #        password: root123456
      # 从库数据源
      #      slave:
      #        enabled: false
      #        url: jdbc:mysql://localhost:3306/cc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: root
      #        password: root123456
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      # 配置默认的监控统计拦截的Filter: stat - SQL监控配置 wall - SQL防火墙配置 slf4j - Druid日志配置
      filters: stat,wall,slf4j
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置连接超时时间
      connect-timeout: 30000
      # 配置网络超时时间
      socket-timeout: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      # 检测连接是否有效的超时时间
      validation-query-timeout: 1
      # 每个连接上PSCache的最大值 如果大于0，pool-prepared-statements自动开启
      max-pool-prepared-statement-per-connection-size: -1
      # 是否开启PSCache，即是否缓存preparedStatement（提升写入、查询效率） 建议在支持游标的数据库开启，例如：Oracle
      pool-prepared-statements: false
      # 检测空闲连接 不影响性能，建议开启
      test-while-idle: true
      # 检测获取连接时的有效性 开启后会影响性能
      test-on-borrow: false
      # 检测归还连接时的有效性 开启后会影响性能
      test-on-return: false
      web-stat-filter:
        # 配置统计页面过滤
        enabled: true
        # 排除路径
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        # 开启session统计
        session-stat-enable: true
        # session统计的最大个数
        session-stat-max-count: 100
        # 过滤路径
        url-pattern: /*
      stat-view-servlet:
        # 配置统计页面
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        reset-enable: false
        # 控制台管理用户名和密码
        login-username: ccnet
        login-password: 123456
  # 日志入库
  aop:
    auto: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  servlet:
    # 文件上传
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  devtools:
    restart:
      # 服务模块 热部署开关
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis-plus
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.cc.net.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*.xml
  # 加载全局的配置文件
  #  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
  global-config:
    banner: true
    db-config:
      id-type: auto

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    root: info
    com.cc: debug
    org.springframework: warn
  file:
    path: ./log/
    name: log/log.log

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    # 访问 UI 自动跳转到 swagger 种
    path: /ui
  packages-to-scan: com.cc.net.controller, com.cc.net.entity

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  url-patterns: /system/*,/monitor/*,/tool/*
