# ??????
cc:
  # ??
  name: CC_SERVER
  # ??
  version: 0.0.1
  # ????
  copyright: 2023
  # ???? ??? Windows??D:/cc/uploadPath?Linux?? /home/cc/uploadPath?
  profile: /
  # ??ip????
  address-enabled: true

# ????
user:
  password:
    # ????{maxRetryCount}???10??
    max-retry-count: 5
    # ????????
    lock-time: 10

# ??????
server:
  # ????HTTP??????80
  port: 8080
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # ?????????????100
    accept-count: 1000
    threads:
      # tomcat?????????200
      max: 1000
      # Tomcat?????????????10
      min-spare: 100

# Spring??
spring:
  # ????
  aop:
    auto: true
  # ????
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  servlet:
    # ????
    multipart:
      # ??????
      max-file-size: 10MB
      # ??????????
      max-request-size: 20MB
  devtools:
    restart:
      # ???? ?????
      enabled: true

# MyBatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  # ???????
  type-aliases-package: com.cc.**.entity
  # ??mapper?????????mapper.xml????
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # ?????????
  #  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
  global-config:
    banner: true
    db-config:
      id-type: auto

# PageHelper????
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

# ????
logging:
  level:
    root: info
    com.cc: debug
    org.springframework: warn
  file:
    path: ./log/
    name: log/log.log

# Shiro
shiro:
  # ????
  login-url: /login
  # ????????
  unauthorized-url: /unauth
  # ????
  index-url: /index
  # ?????
  captcha-enabled: true
  # ????? math ???? char ????
  captcha-type: math
  cookie:
    # ??Cookie??? ????????????
    domain:
    # ??cookie???????
    path: /
    # ??HttpOnly??
    http-only: true
    # ??Cookie??????????
    max-age: 30
    # ???????????????????????main?????Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) ????????????????????????RememberMe Cookie??????????RememberMe Cookie????
    cipher-key:
  session:
    # Session?????-1?????????30???
    expire-time: 43200
    # ??session??????????1???
    db-sync-period: 1
    # ????????session?????????10??
    validation-interval: 10
    # ?????????????2???????????????????????-1????
    max-session: -1
    # ???????/???????????????????
    kickout-after: false
  rememberMe:
    # ???????
    enabled: true

# ??XSS??
xss:
  # ????
  enabled: true
  # ?????????????
  excludes: /system/notice/*
  # ????
  url-patterns: /system/*,/monitor/*,/tool/*

# Swagger??
swagger:
  enabled: true