# 开发环境配置
debug: true
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 1000
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
# Spring 配置
spring:
  application:
    name: serve
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/serve?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root1234
  # 日志入库
  aop:
    auto: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    # 文件上传
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  devtools:
    restart:
      # 服务模块 热部署开关
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# MyBatis-plus 配置
#mybatis-plus:
#  # 搜索指定包别名
#  type-aliases-package: com.cc.serve.**.entity
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapper-locations: classpath*:mapper/**/*.xml
#  # 加载全局的配置文件
#  #  config-location: classpath:mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    auto-mapping-behavior: partial
#    auto-mapping-unknown-column-behavior: warning
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#  global-config:
#    banner: true
#    db-config:
#      id-type: auto
# Redis 配置
#application:
#  redis:
#    host: localhost
#    port: 6380
#    pass: pass
#  security:
#    jwt:
#      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000
#      refresh-token:
#        expiration: 604800000
# PageHelper分页插件
#pagehelper:
#  helper-dialect: mysql
#  support-methods-arguments: true
#  params: count=countSql
# Swagger配置
#springdoc:
#  api-docs:
#    enabled: true
#    path: /api-docs
#  swagger-ui:
#    # 访问 UI 自动跳转到 swagger 种
#    path: /ui
#    tags-sorter: alpha
#    operations-sorter: alpha
#  packages-to-scan: com.cc.serve.controller, com.cc.serve.entity
# 日志
logging:
  level:
    root: info
    com.cc: debug
    org.springframework: error
  file:
    path: ./logs/
    name: logs/log-def.log