# 数据源配置
spring:
  application:
    name: java-serve
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root123456
    druid:
      # 主库数据源
      #      master:
      #        url: jdbc:mysql://localhost:3306/cc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: root
      #        password: root123456
      # 从库数据源
      #      slave:
      #        enabled: false
      #        url: jdbc:mysql://localhost:3306/cc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      #        username: root
      #        password: root123456
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      # 配置默认的监控统计拦截的Filter: stat - SQL监控配置 wall - SQL防火墙配置 slf4j - Druid日志配置
      filters: stat,wall,slf4j
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置连接超时时间
      connect-timeout: 30000
      # 配置网络超时时间
      socket-timeout: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      # 检测连接是否有效的超时时间
      validation-query-timeout: 1
      # 每个连接上PSCache的最大值 如果大于0，pool-prepared-statements自动开启
      max-pool-prepared-statement-per-connection-size: -1
      # 是否开启PSCache，即是否缓存preparedStatement（提升写入、查询效率） 建议在支持游标的数据库开启，例如：Oracle
      pool-prepared-statements: false
      # 检测空闲连接 不影响性能，建议开启
      test-while-idle: true
      # 检测获取连接时的有效性 开启后会影响性能
      test-on-borrow: false
      # 检测归还连接时的有效性 开启后会影响性能
      test-on-return: false
      web-stat-filter:
        # 配置统计页面过滤
        enabled: true
        # 排除路径
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        # 开启session统计
        session-stat-enable: true
        # session统计的最大个数
        session-stat-max-count: 100
        # 过滤路径
        url-pattern: /*
      stat-view-servlet:
        # 配置统计页面
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        reset-enable: false
        # 控制台管理用户名和密码
        login-username: ccnet
        login-password: 123456
