# 项目相关配置
cc:
  # 名称
  name: CC_SERVER
  # 版本
  version: 0.0.1
  # 版权年份
  copyright: 2023
  # 文件路径 示例（ Windows配置D:/cc/uploadPath，Linux配置 /home/cc/uploadPath）
  profile: /
  # 获取ip地址开关
  address-enabled: true

# 用户配置
user:
  # 密码错误{maxRetryCount}次锁定10分钟
  pwd-max-retry-count: 5
  # 密码错误锁定时长
  pwd-lock-time: 10

# 单点登录开关
sso:
  open-flag: false
  sso-client-type: server

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  url-patterns: /system/*,/monitor/*,/tool/*

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 1000
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# Spring配置
spring:
  application:
    name: java-serve
  profiles:
#    active: "@spring.active@" TODO 此处放开替换掉下面的会出错，原因未知
    active: dev
  # 日志入库
  aop:
    auto: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    # 文件上传
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  devtools:
    restart:
      # 服务模块 热部署开关
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Redis
application:
  redis:
    host: localhost
    port: 6380
    pass: pass
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

# MyBatis-plus
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.cc.net.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*.xml
  # 加载全局的配置文件
  #  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
  global-config:
    banner: true
    db-config:
      id-type: auto

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    root: info
    com.cc: debug
    org.springframework: error
  file:
    path: ./log/
    name: log/log.log

# Swagger配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    # 访问 UI 自动跳转到 swagger 种
    path: /ui
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.cc.net.controller, com.cc.net.entity
